# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/python-3.7.11-on-linux_64, last modified Tue Jul 27 13:44:16 2021
# ------------------------------------------------

package:
  name: python
  version: 3.7.11
source:
  - md5: b3671d35b61f5422605cedad32f3457a
    patches:
      - patches/0001-Fix-off-by-one-error-in-_winapi_WaitForMultipleObjec.patch
      - patches/0003-Add-Anaconda-Distribution-version-logic.patch
      - patches/0004-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
      - patches/0005-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
      - patches/0006-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
      - patches/0007-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
      - patches/0008-Support-cross-compiling-byte-code.patch
      - patches/0009-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
      - patches/0010-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
      - patches/0011-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
      - patches/0012-Win32-Do-not-download-externals.patch
      - patches/0013-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch
      - patches/0014-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0015-Disable-new-dtags-in-unixccompiler.py.patch
      - patches/0016-Fix-cross-compilation-on-Debian-based-distros.patch
      - patches/0017-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
      - patches/0018-Unvendor-openssl.patch
      - patches/0019-Unvendor-sqlite3.patch
      - patches/0020-venv-Revert-a-change-from-https-github.com-python-cp.patch
      - patches/0021-Add-CondaEcosystemModifyDllSearchPath.patch
      - patches/0022-Use-ranlib-from-env-if-env-variable-is-set.patch
    url: https://www.python.org/ftp/python/3.7.11/Python-3.7.11.tar.xz
build:
  binary_has_prefix_files:
    - bin/python3.7
    - lib/libpython3.7.*.1.0
    - lib/libpython3.7.a
    - lib/libpython3.7.nolto.a
  detect_binary_files_with_prefix: false
  ignore_run_exports:
    - bzip2
    - libstdcxx-ng
  missing_dso_whitelist:
    - $RPATH/libc.so.6
    - $RPATH/libcrypt.so.1
    - $RPATH/libdl.so.2
    - $RPATH/libm.so.6
    - $RPATH/libnsl.so.1
    - $RPATH/libpthread.so.0
    - $RPATH/libutil.so.1
  no_link: null
  number: '0'
  script_env:
    - PY_INTERP_DEBUG
    - PY_INTERP_LINKAGE_NATURE
  string: h12debd9_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.35.1 h27ae35d_9
    - binutils_linux-64 2.35.1 h454624a_30
    - gcc_impl_linux-64 7.5.0 h7105cf2_17
    - gcc_linux-64 7.5.0 h8f34230_30
    - gxx_impl_linux-64 7.5.0 h0a5bf11_17
    - gxx_linux-64 7.5.0 hffc177d_30
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libgcc-devel_linux-64 7.5.0 hbbeae57_17
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-devel_linux-64 7.5.0 hf0c5c8d_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuuid-cos6-x86_64 2.17.2 4
    - libuuid-devel-cos6-x86_64 2.17.2 4
    - libx11-common-cos6-x86_64 1.6.4 4
    - libx11-cos6-x86_64 1.6.4 4
    - libx11-devel-cos6-x86_64 1.6.4 4
    - make 4.2.1 h1bed415_1
    - patch 2.7.6 h7b6447c_1001
    - pkg-config 0.29.2 h1bed415_8
    - sysroot_linux-64 2.17 h57e8cba_10
    - xorg-x11-proto-devel-cos6-x86_64 7.7 4
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2021.7.5 h06a4308_1
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1k h27cfd23_0
    - readline 8.0 h7b6447c_0
    - sqlite 3.36.0 hc218d9a_0
    - tk 8.6.10 hbc83047_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - ld_impl_linux-64
    - libffi >=3.3,<3.4.0a0
    - libgcc-ng >=7.5.0
    - ncurses >=6.2,<7.0a0
    - openssl >=1.1.1k,<1.1.2a
    - readline >=8.0,<9.0a0
    - sqlite >=3.36.0,<4.0a0
    - tk >=8.6.10,<8.7.0a0
    - xz >=5.2.5,<6.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - python -V
    - python3 -V
    - 2to3 -h
    - pydoc -h
    - python3-config --help
    - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
    - for f in ${CONDA_PREFIX}/lib/python*/_sysconfig*.py; do echo "Checking $f:";
      if [[ `rg @ $f` ]]; then echo "FAILED ON $f"; cat $f; exit 1; fi; done
    - pushd tests
    - pushd distutils
    - python setup.py install -v -v
    - python -c "import foobar"
    - popd
    - pushd distutils.cext
    - python setup.py install -v -v
    - python -v -v -v -c "import greet"
    - python -v -v -v -c "import greet; greet.greet('Python user')" | rg "Hello Python"
    - popd
    - pushd prefix-replacement
    - bash build-and-test.sh
    - popd
    - pushd processpoolexecutor-max_workers-61
    - python ppe.py
    - popd
    - pushd cmake
    - popd
    - popd
  files:
    - tests/cmake/*
    - tests/cython/*
    - tests/distutils.cext/*
    - tests/distutils/*
    - tests/prefix-replacement/*
    - tests/processpoolexecutor-max_workers-61/*
  requires:
    - cmake
    - cython
    - gcc_linux-64 7.5.0.*
    - gxx_linux-64 7.5.0.*
    - ninja
    - ripgrep
    - setuptools
about:
  description: 'Python is a widely used high-level, general-purpose, interpreted,
    dynamic

    programming language. Its design philosophy emphasizes code

    readability, and its syntax allows programmers to express concepts in

    fewer lines of code than would be possible in languages such as C++ or

    Java. The language provides constructs intended to enable clear programs

    on both a small and large scale.

    '
  dev_url: https://docs.python.org/devguide/
  doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
  doc_url: https://www.python.org/doc/versions/
  home: http://www.python.org/
  license: PSF
  license_file: LICENSE
  summary: General purpose programming language
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - isuruf
    - jakirkham
    - jjhelmus
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
