# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Mon Jan 25 20:05:08 2021
# ------------------------------------------------

package:
  name: setuptools
  version: 52.0.0
source:
  patches:
    - 0001-Remove-exact-pinning-on-certifi-and-wincertstore.patch
    - 0002-disable-downloads-inside-conda-build.patch
  sha256: ff0c74d1b905a224d647f99c6135eacbec2620219992186b81aa20012bc7f882
  url: https://github.com/pypa/setuptools/archive/v52.0.0.tar.gz
build:
  number: '0'
  string: py39h06a4308_0
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 main
    - ca-certificates 2021.1.19 h06a4308_0
    - certifi 2020.12.5 py39h06a4308_0
    - ld_impl_linux-64 2.33.1 h53a641e_7
    - libedit 3.1.20191231 h14c3975_1
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.1.0 hdf63c60_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1i h27cfd23_0
    - python 3.9.1 hdb3f193_2
    - readline 8.0 h7b6447c_0
    - sqlite 3.33.0 h62c20be_0
    - tk 8.6.10 hbc83047_0
    - tzdata 2020f h52ac0ba_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - certifi >=2016.9.26
    - python >=3.9,<3.10.0a0
test:
  imports:
    - pkg_resources
    - setuptools
about:
  description: 'Setuptools is a fully-featured, actively-maintained, and stable library

    designed to facilitate packaging Python projects.

    '
  dev_url: https://github.com/pypa/setuptools
  doc_source_url: https://github.com/pypa/setuptools/tree/master/docs
  doc_url: http://pythonhosted.org/setuptools/
  home: https://github.com/pypa/setuptools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Download, build, install, upgrade, and uninstall Python packages
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - mingwandroid
    - msarahan
    - nicoddemus
    - ocefpaf
