# This file created by conda-build 3.21.4
# ------------------------------------------------

package:
  name: python
  version: 3.9.5
source:
  - md5: 71f7ada6bec9cdbf4538adc326120cfd
    patches:
      - patches/0000-Fix-off-by-one-error-in-_winapi_WaitForMultipleObjec.patch
      - patches/0001-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
      - patches/0002-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
      - patches/0003-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
      - patches/0004-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
      - patches/0005-Support-cross-compiling-byte-code.patch
      - patches/0006-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
      - patches/0007-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
      - patches/0008-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
      - patches/0009-Win32-Do-not-download-externals.patch
      - patches/0010-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch
      - patches/0011-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0012-Disable-new-dtags-in-unixccompiler.py.patch
      - patches/0013-Fix-cross-compilation-on-Debian-based-distros.patch
      - patches/0014-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
      - patches/0015-Unvendor-openssl.patch
      - patches/0016-Unvendor-sqlite3.patch
      - patches/0017-venv-Revert-a-change-from-https-github.com-python-cp.patch
      - patches/0018-Win-Add-back-the-DLLSuffix-used-to-find-the-openssl-.patch
      - patches/0019-Use-ranlib-from-env-if-env-variable-is-set.patch
      - patches/0020-Add-CondaEcosystemModifyDllSearchPath.patch
      - patches/0021-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
      - patches/0022-Doing-d1trimfile.patch
      - patches/0023-egg-debugging-with-Windows-debug-builds.patch
      - patches/0024-Add-CONDA_DLL_SEARCH_MODIFICATION_KEEP_GIL-to-aid-de.patch
      - patches/0025-cross-compile-darwin.patch
      - patches/0032-Fix-TZPATH-on-windows.patch
      - patches/0033-gh24324.patch
      - patches/9999-Add-Anaconda-Distribution-version-logic.patch
    url: https://www.python.org/ftp/python/3.9.5/Python-3.9.5.tar.xz
build:
  activate_in_script: true
  detect_binary_files_with_prefix: true
  ignore_run_exports:
    - bzip2
    - gxx_linux-64
  missing_dso_whitelist: null
  no_link: null
  number: 4
  script_env:
    - CONDA_FORGE=no
    - PY_INTERP_DEBUG=no
    - PY_INTERP_LINKAGE_NATURE=static
  skip_compile_pyc: null
  string: h12debd9_4
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.35.1 h27ae35d_9
    - binutils_linux-64 2.35.1 h454624a_30
    - ccache 3.7.9 hfe4627d_0
    - gcc_impl_linux-64 7.5.0 h7105cf2_17
    - gcc_linux-64 7.5.0 h8f34230_30
    - gettext 0.21.0 hf68c758_0
    - gxx_impl_linux-64 7.5.0 h0a5bf11_17
    - gxx_linux-64 7.5.0 hffc177d_30
    - icu 58.2 he6710b0_3
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libgcc-devel_linux-64 7.5.0 hbbeae57_17
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-devel_linux-64 7.5.0 hf0c5c8d_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libtool 2.4.6 h7b6447c_1005
    - libuuid-cos6-x86_64 2.17.2 4
    - libuuid-devel-cos6-x86_64 2.17.2 4
    - libx11-common-cos6-x86_64 1.6.4 4
    - libx11-cos6-x86_64 1.6.4 4
    - libx11-devel-cos6-x86_64 1.6.4 4
    - libxml2 2.9.10 hb55368b_3
    - make 4.2.1 h1bed415_1
    - pkg-config 0.29.2 h1bed415_8
    - ripgrep 12.1.1 0
    - sed 4.8 h7b6447c_0
    - sysroot_linux-64 2.17 h57e8cba_10
    - xorg-x11-proto-devel-cos6-x86_64 7.7 4
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7f8727e_4
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2021.5.25 h06a4308_1
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1k h27cfd23_0
    - readline 8.0 h7b6447c_0
    - sqlite 3.35.4 hdfb4753_0
    - tk 8.6.10 hbc83047_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7f8727e_4
  run:
    - ld_impl_linux-64
    - libffi >=3.3,<3.4.0a0
    - libgcc-ng >=7.5.0
    - libstdcxx-ng >=7.5.0
    - ncurses >=6.2,<7.0a0
    - openssl >=1.1.1k,<1.1.2a
    - readline >=8.0,<9.0a0
    - sqlite >=3.35.4,<4.0a0
    - tk >=8.6.10,<8.7.0a0
    - tzdata
    - xz >=5.2.5,<6.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - python -V
    - python3 -V
    - 2to3 -h
    - pydoc -h
    - python3-config --help
    - python run_test.py
    - python -c "from zoneinfo import ZoneInfo; from datetime import datetime; dt
      = datetime(2020, 10, 31, 12, tzinfo=ZoneInfo('America/Los_Angeles')); print(dt.tzname())"
    - python -m venv test-venv
    - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
    - for f in ${CONDA_PREFIX}/lib/python*/_sysconfig*.py; do echo "Checking $f:";
      if [[ `rg @ $f` ]]; then echo "FAILED ON $f"; cat $f; exit 1; fi; done
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.a
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.nolto.a
    - pushd tests
    - pushd distutils
    - python setup.py install -v -v
    - python -c "import foobar"
    - popd
    - pushd embedding-interpreter
    - bash build-and-test.sh
    - popd
    - pushd cmake
    - bash run_cmake_test.sh 3.9.5
    - popd
    - pushd processpoolexecutor-max_workers-61
    - python ppe.py
    - popd
    - popd
  downstreams:
    - cython
    - setuptools
  files:
    - run_test.py
    - tests/cmake/*
    - tests/cython/*
    - tests/distutils/*
    - tests/embedding-interpreter/*
    - tests/processpoolexecutor-max_workers-61/*
  requires:
    - cmake
    - gcc_linux-64 7.5.0.*
    - gxx_linux-64 7.5.0.*
    - make
    - ninja
    - ripgrep
about:
  description: 'Python is a widely used high-level, general-purpose, interpreted,
    dynamic

    programming language. Its design philosophy emphasizes code

    readability, and its syntax allows programmers to express concepts in

    fewer lines of code than would be possible in languages such as C++ or

    Java. The language provides constructs intended to enable clear programs

    on both a small and large scale.

    '
  dev_url: https://docs.python.org/devguide/
  doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
  doc_url: https://www.python.org/doc/versions/
  home: https://www.python.org/
  license: Python-2.0
  license_file: LICENSE
  summary: General purpose programming language
extra:
  copy_test_source_files: true
  feedstock-name: python
  final: true
  recipe-maintainers:
    - isuruf
    - jakirkham
    - mbargull
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
