# This file created by conda-build 3.21.5
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Tue Oct 26 03:48:41 2021
# ------------------------------------------------

package:
  name: ca-certificates
  version: 2021.10.26
source:
  fn: cacert.pem
  sha256: ae31ecb3c6e9ff3154cb7a55f017090448f88482f0e94ac927c0c67a1f33b9cf
  url: https://curl.haxx.se/ca/cacert-2021-10-26.pem
build:
  commands:
    - /usr/bin/curl --cacert "${PREFIX}/ssl/cacert.pem" https://www.google.com
    - /usr/bin/openssl -CAfile "${PREFIX}/ssl/cacert.pem" -CApath nosuchdir s_client
      -showcerts -connect www.google.com:443
    - test -f "${PREFIX}/ssl/cacert.pem"
    - test -f "${PREFIX}/ssl/cert.pem"
  number: '2'
  string: h06a4308_2
requirements:
  build: []
  run: []
about:
  home: https://github.com/conda-forge/ca-certificates-feedstock
  license: MPL 2.0
  license_file: LICENSE.txt
  summary: Certificates for use with other packages.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
