# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Mon Apr 12 21:15:20 2021
# ------------------------------------------------

package:
  name: conda-package-handling
  version: 1.7.3
source:
  fn: conda-package-handling-1.7.3.tar.gz
  patches:
    - 0002-punt-test_secure_refusal.patch
  sha256: d908640a7fd6ec789afb3dc8ecdebef145f3c5dfdd4fa89dc866ea69edeea122
  url: https://github.com/conda/conda-package-handling/releases/download/1.7.3/conda-package-handling-1.7.3.tar.gz
build:
  entry_points:
    - cph = conda_package_handling.cli:main
  missing_dso_whitelist: null
  number: '1'
  script: /tmp/build/80754af9/conda-package-handling_1618262147379/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps -vv
  string: py39h27cfd23_1
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - binutils_impl_linux-64 2.33.1 he6710b0_7
    - binutils_linux-64 2.33.1 h9595d00_15
    - gcc_impl_linux-64 7.3.0 habb00fd_1
    - gcc_linux-64 7.3.0 h553295d_15
    - ld_impl_linux-64 2.33.1 h53a641e_7
    - libgcc-ng 9.1.0 hdf63c60_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
  host:
    - _libarchive_static_for_cph 3.4.3 h14c3975_2
    - _libgcc_mutex 0.1 main
    - ca-certificates 2021.1.19 h06a4308_1
    - certifi 2020.12.5 py39h06a4308_0
    - cython 0.29.22 py39h2531618_0
    - ld_impl_linux-64 2.33.1 h53a641e_7
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.1.0 hdf63c60_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1k h27cfd23_0
    - pip 21.0.1 py39h06a4308_0
    - python 3.9.2 hdb3f193_0
    - readline 8.1 h27cfd23_0
    - setuptools 52.0.0 py39h06a4308_0
    - sqlite 3.35.4 hdfb4753_0
    - tk 8.6.10 hbc83047_0
    - tzdata 2020f h52ac0ba_0
    - wheel 0.36.2 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - libgcc-ng >=7.3.0
    - python >=3.9,<3.10.0a0
    - six
    - tqdm
test:
  commands:
    - pytest tests
  imports:
    - conda_package_handling
    - conda_package_handling.archive_utils_cy
  requires:
    - mock
    - pytest
    - pytest-cov
    - pytest-mock
  source_files:
    - tests
about:
  home: https://github.com/conda/conda-package-handling
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - static_deps_licenses/bzip2.txt
    - static_deps_licenses/libarchive.txt
    - static_deps_licenses/zlib.txt
    - static_deps_licenses/zstd.txt
  summary: Create and extract conda packages of various formats
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jjhelmus
    - mingwandroid
    - msarahan
